authors = ["Boom Token <marinachris112@outlook.com>"]
description = "Boom Token Lab’s Fastly Compute Starter Kit for TypeScript. This repository is a template for deploying high-performance Fastly Compute@Edge applications using JavaScript and TypeScript."
language = "javascript_typescript"
manifest_version = 3
name = "boom-fastly-compute-kit"

[scripts]
build = "npm run build"
post_init = "npm install"
