on: pull_request
name: Test
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Setup Fastly CLI
      uses: fastly/compute-actions/setup@v11
    - name: Install Dependencies
      run: npm install
    - name: Build Compute Package
      uses: fastly/compute-actions/build@v11
      with:
        verbose: true
